name: gm_cafe
description: "Gadung Melati Cafe - Kasir"
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.2+1
  sqlite3_flutter_libs: ^0.5.21
  path: ^1.8.3
  intl: ^0.18.1
  qr_flutter: ^4.1.0
  image_picker: ^1.0.4
  shared_preferences: ^2.2.1
  # blue_thermal_printer: ^1.2.3
  permission_handler: ^11.3.1
  excel: ^4.0.0
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
