name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Ganti ke master jika branch utama Anda master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release --base-href "/gm-cafe/" 
        # Note: --base-href harus sesuai dengan nama repository GitHub Anda

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web
          branch: gh-pages # Hasil build akan dikirim ke branch ini
